version: '3'

services:
  api:
    container_name: web
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/
    ports:
      - 5001:5000
      - 5555:5555
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./services/web/database:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_MULTIPLE_DATABASES=db_dev,db_test
  # docs:
  #   container_name: docs
  #   image: swaggerapi/swagger-ui:3.28.0
  #   build: .
  #   ports:
  #     - 8000:8080
volumes:
  postgres_data:
