service: calculator
provider:
  name: aws
  runtime: python3.12
  stage: dev
  region: us-east-2
  vpc:
    securityGroupIds:
      - sg-064c35cf30f657313
    subnetIds:
      - subnet-0e6d30d7315ac8d0c
      - subnet-010645b83cf5057cf
      - subnet-0278845d9a013ae2b
  environment:
    FLASK_SQLALCHEMY_DATABASE_URI: 'postgresql://postgres:g1Qgs6IDAEnaOkZWEXMK@database-lp-calculator.cl2080wsatbq.us-east-2.rds.amazonaws.com:5432/db_dev'
    FLASK_APP: 'project/__init__.py'
    FLASK_ENV: 'development'
    FLASK_APP_NAME: 'Calculator API'
    FLASK_APP_FOLDER: '/usr/src/app'
    FLASK_SECRET_KEY: '0000000000000000000000000000000000000000000000000000000'
    FLASK_DEBUG: 'False'
    FLASK_TESTING: 'False'
    FLASK_LOGGING_FORMAT: '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
    FLASK_LOGGING_LOCATION: 'logs/flask.log'
    FLASK_LOGGING_LEVEL: 'DEBUG'
    FLASK_SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
    FLASK_ITEMS_PER_PAGE: '10'
    FLASK_MAX_PER_PAGE: '100'
    FLASK_DATE_FORMAT: '%m-%d-%Y, %H:%M:%S'
  memorySize: 128
  # deploymentBucket:
  #   name: serverless-deployments
plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-offline
custom:
  wsgi:
    app: app.app
    packRequirements: false
  python_requirements:
    dockerFile: DockerFile
functions:
 app:
   handler: wsgi_handler.handler
   events:
      - httpApi: '*'